sudo: required
dist: trusty
group: deprecated-2017Q4

services:
  - docker

language: c

env:
  - TARGET_DISTRIBUTION=debian8
  - TARGET_DISTRIBUTION=debian9
  - TARGET_DISTRIBUTION=ubuntu1404
  - TARGET_DISTRIBUTION=ubuntu1604
  - TARGET_DISTRIBUTION=ubuntu1804

addons:
  hosts:
    - 127.0.0.1.XIP.IO

script:
  - make "$TARGET_DISTRIBUTION"

before_deploy:
  - make bintray

deploy:
  - provider: bintray
    user: tatsushid
    key: '$BINTRAY_API_KEY'
    file: ./bintray/bintray-h2o.json
    skip_cleanup: true
  - provider: bintray
    user: tatsushid
    key: '$BINTRAY_API_KEY'
    file: ./bintray/bintray-h2o-doc.json
    skip_cleanup: true
  - provider: bintray
    user: tatsushid
    key: '$BINTRAY_API_KEY'
    file: ./bintray/bintray-h2o-dbg.json
    skip_cleanup: true
  - provider: bintray
    user: tatsushid
    key: '$BINTRAY_API_KEY'
    file: ./bintray/bintray-libh2o0.json
    skip_cleanup: true
  - provider: bintray
    user: tatsushid
    key: '$BINTRAY_API_KEY'
    file: ./bintray/bintray-libh2o-evloop0.json
    skip_cleanup: true
  - provider: bintray
    user: tatsushid
    key: '$BINTRAY_API_KEY'
    file: ./bintray/bintray-libh2o-dev-common.json
    skip_cleanup: true
  - provider: bintray
    user: tatsushid
    key: '$BINTRAY_API_KEY'
    file: ./bintray/bintray-libh2o-dev.json
    skip_cleanup: true
  - provider: bintray
    user: tatsushid
    key: '$BINTRAY_API_KEY'
    file: ./bintray/bintray-libh2o-evloop-dev.json
    skip_cleanup: true
